# Generated by Django 4.2.3 on 2023-07-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0002_remove_dispatchentryassets_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchentryassets',
            name='model',
            field=models.CharField(default='Model', max_length=100),
            preserve_default=False,
        ),
    ]
