# Generated by Django 4.2.3 on 2023-07-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0003_dispatchentryassets_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchentryassets',
            name='model',
        ),
    ]
